### PR TITLE
Feature/pick up manager 60

### LINKED ISSUE #60: Pick Up Manager

### PR DESCRIPTION
**Pull request by fpdotmonkey**
Tests: (let me know if this is a useful format for presenting them)

Open `Assets/Scenes/PickUpManagerTests.unity` and execute each of these scenarios

Given a Player Character that you can move up, down, left, right with WASD and is a Pick Up Carrier
And an item that is a Pick Up Item
When the player character enters collision with the Pick Up Item
Then the Pick Up Item will become a child of the Player Character

Given a Player Character that you can move up, down, left, right with WASD and is a Pick Up Carrier
And an item that is a Pick Up Item that is a child of the Player Character
And an item that is a Pick Up Receiver
When the Pick Up Item enters collision with the Pick Up Receiver
Then the Pick Up Item is consumed

Given a Player Character that you can move up, down, left, right with WASD and is a Pick Up Carrier
And an item that is a Pick Up Item with a "food" attribute that is a child of the Player Character
And an item that is a Pick Up Receiver
When the Pick Up Item enters collision with the Pick Up Receiver
Then the Pick Up Receiver will print a debug line "I got some food"

Given a Player Character that you can move up, down, left, right with WASD and is a Pick Up Carrier
And 2 items that are Pick Up Items
When the Player Character captures one of them
And attempts to capture the other
Then nothing will happen

Given a Player Character that you can move up, down, left, right with WASD and is a Pick Up Carrier
And an item that is a Pick Up Item
And an item that is a Pick Up Receiver
When the Player Character captures the Pick Up Item
And collides with the Pick Up Receiver without the Pick Up Item also colliding with the Pick Up Receiver
Then a message will not be written to the debug console.

Given an item that is a Pick Up Item
When a user hovers their mouse over the Item Type property in the editor
Then a message describing what the Item Type property is will appear.

Closes #60

### CODE REVIEW

**Review by Coolbots7 — CHANGES_REQUESTED** [review]
Compiler error in ```Assets/Scripts/Core/PickUpItem```

**Review by Coolbots7 — CHANGES_REQUESTED** [review]
PickUpItem Item Type should be some sort of controlled input instead of a free text input. Booleans with check boxes? enum with dropdown? Not sure if all item types will be mutually exclusive, if not maybe the boolean is better.

**Review by Coolbots7 — CHANGES_REQUESTED** [review]
I noticed an odd behavior where "I got some food" is printed in the console but the Pick Up Item is not consumed.

To Recreate: Collide with a Pick Up Item with the Item Type "food" on one side of the Player Character. Then go around the Pick Up Receiver so the Player Character is between the two and collide with the Pick Up Receiver using the Player Character.

**Comment by fpdotmonkey** [comment]
Fixed the problems, added a couple more tests

**Review by Coolbots7 — APPROVED** [review]

**Pull request merged**
